In [ ]:
#Numpy Numpy is the primary way to handle matrices and vectors in python.Numpy is the most popular python library for matrix/vector computations. 
#3.1.1 Importing numpy
Numpy is typically imported as np:


import numpy as np


# 3.1.2 Array: The Fundamental Data Structure in Numpy
For 1D Array 
    a = np.array([1,2,3,4])
    print("a:\n", a)
##  a:
##  [1 2 3 4]   

For 2D Array
b = np.array([[1,2], [3,4]])
print("b:\n", b)
## b:
##  [[1 2]
##  [3 4]]

# 01. Get Dimension
a.ndim




#tuple:

a.shape
## (4,)
b.shape
## (2, 2)

#we can reshape the length-4 vector into a 2x2 matrix as

a.reshape((2,2))
## array([[1, 2],
##        [3, 4]])
# and we can “straighten” matrix b into a vector with

b.reshape((4,))
## array([1, 2, 3, 4])

3.1.3 Creating Arrays

np.arange(10)  # vector of length 10
## array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(10).reshape((2,5))  # 2x5 matrix
## array([[0, 1, 2, 3, 4],
##        [5, 6, 7, 8, 9]])
np.zeros and np.ones create arrays filled with zeros and ones respectively:

np.zeros((5,))
## array([0., 0., 0., 0., 0.])
np.ones((2,4))
## array([[1., 1., 1., 1.],
##        [1., 1., 1., 1.]])



In [ ]:
# get dimension

In [ ]:
a.ndim